### ISSUE TITLE
Game over when planet health reaches 0

### ISSUE THREAD

**Issue by L3NNYY** [L3NNYY/AppGame#11]
Get some sort of end game screen to fade in when you lose that will pause the game, this will also address pausing the game, since the functionality will now be there, just a button that will need to be added.

relates to epic #7

**Comment by arkzuch** [comment]
Right now instead of going to end game screen the game goes straight to main menu. I'll change it once I implement the death screen. Pausing will be very easy to do as it is just one line of code (Time.setScale = 0f;). Will implement the death screen next time I work on the project.

**Comment by L3NNYY** [comment]
+1 very nice change
