### ISSUE TITLE
Create start menu screen

### ISSUE THREAD

**Issue by L3NNYY** [L3NNYY/AppGame#12]
Find out how unity allows for menu creation and transition between different screens. Do we need to implement our own screen managers or does unity have the ability to manage screens and connect transitions.

addresses #7 

**The start menu screen should include:**

- [x] Settings Button (does not need to function yet, would be nice if it takes us to an empty screen ready for settings menu development)

- [x] Start Game Button (starts our main game)

**Comment by L3NNYY** [comment]
@anb2k has made progress on this already

**Comment by JackoKov** [comment]
Stop emailing me
