### ISSUE TITLE
Improve power-up pathing & spawn

### ISSUE THREAD

**Issue by L3NNYY** [L3NNYY/AppGame#30]
Instead of having them spawn from the same side, it would be cool if they: 

- spawned from both sides
- spawned in different sizes ??
- spawned with different speeds

@anb2k did asteroid movement, he can help with task or give guidance.

**Comment by arkzuch** [comment]
I'll work on it

**Comment by arkzuch** [comment]
Completed the task

**Comment by arkzuch** [comment]
Can't seem to be able to close this issue from my phone
