### ISSUE TITLE
Add score multipliers

### ISSUE THREAD

**Issue by L3NNYY** [L3NNYY/AppGame#32]
The score should multiply/react to the user destroying asteroids without missing a click/press and the combo should reset if the user misses a click or stops for a long enough period of time.

Take fruit ninja as an example.

Another task will include animating the score text so that it changes colours and has effects such as popping bigger and smaller.

**Comment by arkzuch** [comment]
I managed to get the multiplier to increase by 1 for every 5 destroyed asteroids. However I found it tricky to reset the multiplier to 1 when the player misses.
