### ISSUE TITLE
Add UI (Main Menu, Pause Screen, Settings Menu)

### ISSUE THREAD

**Issue by JackoKov** [L3NNYY/AppGame#7]
Add a user interface that will have different scenes that it can load between where it will have buttons or sliders to navigate between. These will have a smooth transition with either loading screens or transition between the scenes. The menu's will have some Menu music or background audio but these will come later and are seen on the [Kanban Issue #6](https://github.com/L3NNYY/AppGame/issues/6)

Add additional separate issues for different Menus these can be done when they are being worked on.

- [x] Main Menu
- [x] Pause Menu
- [x] Settings Menu

@JackoKov Have created UI in Unity so I can look further into this.

**Comment by JackoKov** [comment]
Add additional separate Issue's for different Menu's these can be done when they are being worked on.

- [ ] Main Menu
- [ ] Pause Menu
- [ ] Settings Menu

**Comment by arkzuch** [comment]
Added a functioning pause screen.
Pops up when ESC clicked.

**Comment by L3NNYY** [comment]
Settings menu may not be included - it may be small enough to go straight onto the pause and menu screen without its own scene
